CREATE TABLE TB_Curso
(ID_CURSO number(6),
NM_CURSO varchar2(50) CONSTRAINT NOME_NN NOT NULL,
DS_DEPARTAMENTO VARCHAR2(50) CONSTRAINT DEPARTAMENTO_NN NOT NULL,
CONSTRAINT CODCURSO_PK PRIMARY KEY (ID_CURSO));

CREATE TABLE TB_Aluno
(ID_RGM number(6),
NM_ALUNO varchar2(50) CONSTRAINT ALUNO_NOME_NN NOT NULL,
DS_ENDERECO VARCHAR2(50) CONSTRAINT ENDERECO_NN NOT NULL,
DS_BAIRRO VARCHAR2(50) CONSTRAINT BAIRRO_NN NOT NULL,
DS_CIDADE VARCHAR2(50) CONSTRAINT CIDADE_NN NOT NULL,
ID_CEP VARCHAR2(8) CONSTRAINT CEP_NN NOT NULL,
DS_SENHA VARCHAR2(15) CONSTRAINT SENHA_NN NOT NULL,
ID_CURSO NUMBER(6) CONSTRAINT ALUNO_CODCURSO_NN NOT NULL,
CONSTRAINT RGM_PK PRIMARY KEY (ID_RGM),
CONSTRAINT Curso_CODCURSO_FK FOREIGN KEY (ID_CURSO) REFERENCES TB_CURSO(ID_CURSO));

CREATE TABLE TB_Emprestimo
(ID_EMPRESTIMO number(6),
NM_BIBLIOTECARIO varchar2(50) CONSTRAINT BLIBIOTECARIO_NN NOT NULL,
DT_EMPRESTIMO DATE CONSTRAINT DATAEMP_NN NOT NULL,
DT_DEVOLUCAO DATE CONSTRAINT DATADEV_NN NOT NULL,
DT_PREVISAO DATE CONSTRAINT DATAPREV_NN NOT NULL,
ID_RGM NUMBER(6),
CONSTRAINT CODEMP_PK PRIMARY KEY (ID_EMPRESTIMO),
CONSTRAINT ALUNO_RGM_FK FOREIGN KEY (ID_RGM) REFERENCES TB_ALUNO(ID_RGM));

CREATE TABLE TB_LIVRO
(ID_LIVRO number(6),
NM_LIVRO varchar2(50) CONSTRAINT LIVRO_NOME_NN NOT NULL,
NM_EDITORA VARCHAR2(50) CONSTRAINT EDITORA_NN NOT NULL,
NM_AUTOR VARCHAR2(50) CONSTRAINT AUTOR_NN NOT NULL,
DS_VOLUME VARCHAR2(50) CONSTRAINT VOLUME_NN NOT NULL,
VL_VALOR number(12,2) CONSTRAINT VALOR_NN NOT NULL,
CONSTRAINT LIVRO_ID_LIVRO_PK PRIMARY KEY (ID_LIVRO));

CREATE TABLE TB_EXEMPLAR
(ID_EXEMPLAR number(6),
ID_LIVRO number(6),
FL_SITUACAO VARCHAR2(1) CONSTRAINT SITUACAO_NN NOT NULL,
CONSTRAINT EXEMPLAR_SITUACAO_CK CHECK(FL_SITUACAO in ('S', 'N')),
CONSTRAINT EXEMPLAR_PK PRIMARY KEY (ID_EXEMPLAR, ID_LIVRO),
CONSTRAINT EXEMPLAR_ID_LIVRO_FK FOREIGN KEY (ID_LIVRO) REFERENCES TB_LIVRO(ID_LIVRO));

CREATE TABLE TB_ITENS_EMPR
(ID_EMPRESTIMO number(6),
ID_EXEMPLAR number(6),
ID_LIVRO number(6),
OBSERVACAO VARCHAR2(50) CONSTRAINT OBSERVACAO_NN NOT NULL,
CONSTRAINT ITENSEMPRESTIMO_PK PRIMARY KEY (ID_EMPRESTIMO, ID_EXEMPLAR, ID_LIVRO),
CONSTRAINT EMPRESTIMO_FK FOREIGN KEY (ID_EMPRESTIMO) REFERENCES TB_EMPRESTIMO(ID_EMPRESTIMO),
CONSTRAINT ITENSEMPRESTIMO_FK FOREIGN KEY (ID_EXEMPLAR,ID_LIVRO) REFERENCES TB_EXEMPLAR (ID_EXEMPLAR, ID_LIVRO));
