create table TB_CONVENIO(
ID_CONVENIO NUMBER(6),
NM_CONVENIO VARCHAR2(50)constraint CONVENIO_NOME_NN not null,
NR_CNPJ     VARCHAR2(25)constraint CONVENIO_CNPJ_NN not null,
NM_CONTATO  VARCHAR2(50),
constraint CONVENIO_ID_CONVENIO_PK primary key(ID_CONVENIO));

create table TB_EXAME(
ID_EXAME NUMBER(6),
NM_EXAME VARCHAR2(50)constraint EXAME_NOME_NN not null,
constraint EXAME_CODIGO_EXAME_PK primary key(ID_EXAME));

create table TB_ESPECIALIDADE(
ID_ESPECIALIDADE NUMBER(6),
NM_ESPECIALIDADE VARCHAR2(50)constraint ESPECIALIDADE_NOME_NN not null,
constraint ESPECIALIDADE_ID_ESPEC_PK primary key(ID_ESPECIALIDADE));

create table TB_PACIENTE(
ID_PACIENTE NUMBER(6),
NM_PACIENTE VARCHAR2(50)constraint PACIENTE_NOME_NN not null,
DS_ENDERECO VARCHAR2(50)constraint PACIENTE_ENDERECO_NN not null,
DS_BAIRRO   VARCHAR2(40)constraint PACIENTE_BAIRRO_NN not null,
NR_DDD      VARCHAR2(2)constraint PACIENTE_DDD_NN not null,
NR_TELEFONE VARCHAR2(8)constraint PACIENTE_TELEFONE_NN not null,
constraint PACIENTE_ID_PACIENTE_PK primary key(ID_PACIENTE));

create table TB_MEDICO(
ID_MEDICO        NUMBER(6),
NM_MEDICO        VARCHAR2(50)constraint MEDICO_NOME_NN not null,
ID_ESPECIALIDADE NUMBER(6)   constraint MEDICO_COD_ESPECIALIDADE_NN not null,
constraint MEDICO_ID_ESPECIALIDADE_fk foreign key (ID_ESPECIALIDADE) references 
TB_ESPECIALIDADE(ID_ESPECIALIDADE),
constraint MEDICO_ID_MEDICO_PK primary key(ID_MEDICO));

CREATE TABLE TB_EXAMES_REALIZADOS(
ID_EXAME_REALIZADO NUMBER(6),
ID_PACIENTE        NUMBER(6)    CONSTRAINT EXAMESREAL_COD_PACIENTE_NN NOT NULL,
ID_CONVENIO        NUMBER(6)    CONSTRAINT EXAMESREAL_COD_CONVENIO_NN NOT NULL,
ID_EXAME           NUMBER(6)    CONSTRAINT EXAMESREAL_COD_EXAME_NN NOT NULL,
ID_MEDICO          NUMBER(6)    CONSTRAINT EXAMESREAL_COD_MEDICO_NN NOT NULL,
DS_DIAGNOSTICO     VARCHAR2(255)CONSTRAINT EXAMESREAL_DIAGNOSTICO_NN NOT NULL,
DT_EXAME           DATE         CONSTRAINT EXAMESREAL_DATA_EXAME_NN NOT NULL,
constraint EXAMESREAL_ID_PACIENTE_fk foreign key (ID_PACIENTE) references 
TB_PACIENTE(ID_PACIENTE),
constraint EXAMESREAL_ID_CONVENIO_fk foreign key (ID_CONVENIO) references 
TB_CONVENIO(ID_CONVENIO),
constraint EXAMESREAL_ID_EXAME_fk foreign key (ID_EXAME) references TB_EXAME(ID_EXAME),
constraint EXAMESREAL_ID_MEDICO_fk foreign key (ID_MEDICO) references TB_MEDICO(ID_MEDICO),
CONSTRAINT EXAMESREAL_ID_EXAME_REAL_PK PRIMARY KEY(ID_EXAME_REALIZADO));
